In [2]:
import sys
# sys.path is a list of absolute path strings
sys.path.append('/mnt/sda/boris_stanoev/PropStar/')

In [3]:
from normalization.normalize import Normalize
from sklearn.datasets import fetch_openml

In [4]:
data = fetch_openml(name='mushroom')
denormalized_table = data.data.join(data.target)

/mnt/sda/boris_stanoev/PropStar/venv/lib/python3.10/site-packages/sklearn/datasets/_openml.py:303: UserWarning: Multiple active versions of the dataset matching the name mushroom exist. Versions may be fundamentally different, returning version 1.
  warn(
/mnt/sda/boris_stanoev/PropStar/venv/lib/python3.10/site-packages/sklearn/datasets/_openml.py:1002: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(

In [9]:
denormalized_table.rename(columns={'bruises%3F':'bruises'}, inplace=True)

In [11]:
denormalized_table.columns.values

array(['cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat', 'class'],
      dtype=object)

In [26]:
cap_columns = ['cap-shape', 'cap-surface', 'cap-color']
gill_columns = ['gill-attachment', 'gill-spacing', 'gill-size', 'gill-color']
stalk_columns = ['stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring']
veil_columns = ['veil-type', 'veil-color']
ring_columns = ['ring-number', 'ring-type']
spore_print_color_columns = ['spore-print-color']
mushroom_columns = ['bruises', 'odor', 'population', 'habitat', 'class']
all_columns = denormalized_table.columns.values

In [18]:
print(denormalized_table[[*cap_columns]].count())
print(denormalized_table[[*cap_columns]].drop_duplicates().count())

cap-shape      8124
cap-surface    8124
cap-color      8124
dtype: int64
cap-shape      90
cap-surface    90
cap-color      90
dtype: int64

In [19]:
print(denormalized_table[[*gill_columns]].count())
print(denormalized_table[[*gill_columns]].drop_duplicates().count())

gill-attachment    8124
gill-spacing       8124
gill-size          8124
gill-color         8124
dtype: int64
gill-attachment    34
gill-spacing       34
gill-size          34
gill-color         34
dtype: int64

In [21]:
print(denormalized_table[[*stalk_columns]].count())
print(denormalized_table[[*stalk_columns]].drop_duplicates().count())

stalk-shape                 8124
stalk-root                  5644
stalk-surface-above-ring    8124
stalk-surface-below-ring    8124
stalk-color-above-ring      8124
stalk-color-below-ring      8124
dtype: int64
stalk-shape                 63
stalk-root                  36
stalk-surface-above-ring    63
stalk-surface-below-ring    63
stalk-color-above-ring      63
stalk-color-below-ring      63
dtype: int64

In [23]:
print(denormalized_table[[*veil_columns]].count())
print(denormalized_table[[*veil_columns]].drop_duplicates().count())

veil-type     8124
veil-color    8124
dtype: int64
veil-type     4
veil-color    4
dtype: int64

In [24]:
print(denormalized_table[[*ring_columns]].count())
print(denormalized_table[[*ring_columns]].drop_duplicates().count())

ring-number    8124
ring-type      8124
dtype: int64
ring-number    7
ring-type      7
dtype: int64

In [22]:
denormalized_table[[*stalk_columns]]

,stalk-shape,stalk-root,stalk-surface-above-ring,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring
0,e,e,s,s,w,w
1,e,c,s,s,w,w
2,e,c,s,s,w,w
3,e,e,s,s,w,w
4,t,e,s,s,w,w
...,...,...,...,...,...,...
8119,e,NaN,s,s,o,o
8120,e,NaN,s,s,o,o
8121,e,NaN,s,s,o,o
8122,t,NaN,s,k,w,w
8123,e,NaN,s,s,o,o

In [25]:
norm = Normalize(denormalized_table=denormalized_table, denormalized_table_name="original_table")

In [27]:
norm.create_entity(source_entity_name="original_table", target_entity_name="mushroom", columns=all_columns,
                   distinct_values=True, retain_columns=['mushroom_id'])

In [29]:
norm.create_entity(source_entity_name="mushroom", target_entity_name="cap", columns=cap_columns,
                   distinct_values=True, retain_columns=['mushroom_id'])

In [30]:
norm.create_entity(source_entity_name="mushroom", target_entity_name="gill", columns=gill_columns,
                   distinct_values=True, retain_columns=['mushroom_id'])

In [31]:
norm.create_entity(source_entity_name="mushroom", target_entity_name="stalk", columns=stalk_columns,
                   distinct_values=True, retain_columns=['mushroom_id'])

In [32]:
norm.create_entity(source_entity_name="mushroom", target_entity_name="veil", columns=veil_columns,
                   distinct_values=True, retain_columns=['mushroom_id'])

In [33]:
norm.create_entity(source_entity_name="mushroom", target_entity_name="ring", columns=ring_columns,
                   distinct_values=True, retain_columns=['mushroom_id'])

In [34]:
norm.create_entity(source_entity_name="mushroom", target_entity_name="spore_print_color_type", columns=spore_print_color_columns,
                   distinct_values=True, retain_columns=['mushroom_id'])

dict_keys(['original_table', 'mushroom', 'cap', 'gill', 'stalk', 'veil', 'ring', 'spore_print_color_type'])

In [36]:
norm.create_entity(source_entity_name="mushroom", target_entity_name="bruises_type", columns=['bruises'],
                   distinct_values=True)

norm.create_entity(source_entity_name="mushroom", target_entity_name="odor_type", columns=['odor'],
                   distinct_values=True)
norm.create_entity(source_entity_name="mushroom", target_entity_name="population_type", columns=['population'],
                   distinct_values=True)
norm.create_entity(source_entity_name="mushroom", target_entity_name="habitat_type", columns=['habitat'],
                   distinct_values=True)

In [39]:
norm.remove_entity("original_table")

In [40]:
print(norm.primary_keys)
print("\n")
print(norm.relations)
print("\n")
print(norm.entity_set.keys())

{'mushroom': 'mushroom_id', 'cap': 'cap_id', 'gill': 'gill_id', 'stalk': 'stalk_id', 'veil': 'veil_id', 'ring': 'ring_id', 'spore_print_color_type': 'spore_print_color_type_id', 'bruises_type': 'bruises_type_id', 'odor_type': 'odor_type_id', 'population_type': 'population_type_id', 'habitat_type': 'habitat_type_id'}


{'mushroom': {}, 'cap': {'mushroom': ('cap_id', 'cap_id')}, 'gill': {'mushroom': ('gill_id', 'gill_id')}, 'stalk': {'mushroom': ('stalk_id', 'stalk_id')}, 'veil': {'mushroom': ('veil_id', 'veil_id')}, 'ring': {'mushroom': ('ring_id', 'ring_id')}, 'spore_print_color_type': {'mushroom': ('spore_print_color_type_id', 'spore_print_color_type_id')}, 'bruises_type': {'mushroom': ('bruises_type_id', 'bruises_type_id')}, 'odor_type': {'mushroom': ('odor_type_id', 'odor_type_id')}, 'population_type': {'mushroom': ('population_type_id', 'population_type_id')}, 'habitat_type': {'mushroom': ('habitat_type_id', 'habitat_type_id')}}


dict_keys(['mushroom', 'cap', 'gill', 'stalk', 'veil', 'ring', 'spore_print_color_type', 'bruises_type', 'odor_type', 'population_type', 'habitat_type'])

In [41]:
for entity in norm.entity_set.keys():
    print(
        f"ALTER TABLE {entity} ADD CONSTRAINT PK_{entity} PRIMARY KEY ({norm.primary_keys[entity]});")

for parent_table in norm.relations:
    for child_table in norm.relations[parent_table]:
        print(f"ALTER TABLE {child_table} ADD CONSTRAINT FK_{child_table}_{parent_table} "
              f"FOREIGN KEY ({norm.relations[parent_table][child_table][1]}) "
              f"REFERENCES {parent_table}({norm.relations[parent_table][child_table][0]}));")

ALTER TABLE mushroom ADD CONSTRAINT PK_mushroom PRIMARY KEY (mushroom_id);
ALTER TABLE cap ADD CONSTRAINT PK_cap PRIMARY KEY (cap_id);
ALTER TABLE gill ADD CONSTRAINT PK_gill PRIMARY KEY (gill_id);
ALTER TABLE stalk ADD CONSTRAINT PK_stalk PRIMARY KEY (stalk_id);
ALTER TABLE veil ADD CONSTRAINT PK_veil PRIMARY KEY (veil_id);
ALTER TABLE ring ADD CONSTRAINT PK_ring PRIMARY KEY (ring_id);
ALTER TABLE spore_print_color_type ADD CONSTRAINT PK_spore_print_color_type PRIMARY KEY (spore_print_color_type_id);
ALTER TABLE bruises_type ADD CONSTRAINT PK_bruises_type PRIMARY KEY (bruises_type_id);
ALTER TABLE odor_type ADD CONSTRAINT PK_odor_type PRIMARY KEY (odor_type_id);
ALTER TABLE population_type ADD CONSTRAINT PK_population_type PRIMARY KEY (population_type_id);
ALTER TABLE habitat_type ADD CONSTRAINT PK_habitat_type PRIMARY KEY (habitat_type_id);
ALTER TABLE mushroom ADD CONSTRAINT FK_mushroom_cap FOREIGN KEY (cap_id) REFERENCES cap(cap_id));
ALTER TABLE mushroom ADD CONSTRAINT FK_mushroom_gill FOREIGN KEY (gill_id) REFERENCES gill(gill_id));
ALTER TABLE mushroom ADD CONSTRAINT FK_mushroom_stalk FOREIGN KEY (stalk_id) REFERENCES stalk(stalk_id));
ALTER TABLE mushroom ADD CONSTRAINT FK_mushroom_veil FOREIGN KEY (veil_id) REFERENCES veil(veil_id));
ALTER TABLE mushroom ADD CONSTRAINT FK_mushroom_ring FOREIGN KEY (ring_id) REFERENCES ring(ring_id));
ALTER TABLE mushroom ADD CONSTRAINT FK_mushroom_spore_print_color_type FOREIGN KEY (spore_print_color_type_id) REFERENCES spore_print_color_type(spore_print_color_type_id));
ALTER TABLE mushroom ADD CONSTRAINT FK_mushroom_bruises_type FOREIGN KEY (bruises_type_id) REFERENCES bruises_type(bruises_type_id));
ALTER TABLE mushroom ADD CONSTRAINT FK_mushroom_odor_type FOREIGN KEY (odor_type_id) REFERENCES odor_type(odor_type_id));
ALTER TABLE mushroom ADD CONSTRAINT FK_mushroom_population_type FOREIGN KEY (population_type_id) REFERENCES population_type(population_type_id));
ALTER TABLE mushroom ADD CONSTRAINT FK_mushroom_habitat_type FOREIGN KEY (habitat_type_id) REFERENCES habitat_type(habitat_type_id));

In [42]:
norm.persist_entity_set(database_name="mushroom_exp1")

2023-09-15 23:08:24,086 INFO sqlalchemy.engine.Engine SELECT CAST(SERVERPROPERTY('ProductVersion') AS VARCHAR)
2023-09-15 23:08:24,087 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-09-15 23:08:24,088 INFO sqlalchemy.engine.Engine SELECT schema_name()
2023-09-15 23:08:24,089 INFO sqlalchemy.engine.Engine [generated in 0.00053s] ()
2023-09-15 23:08:24,090 INFO sqlalchemy.engine.Engine SELECT CAST('test max support' AS NVARCHAR(max))
2023-09-15 23:08:24,091 INFO sqlalchemy.engine.Engine [generated in 0.00053s] ()
2023-09-15 23:08:24,092 INFO sqlalchemy.engine.Engine SELECT 1 FROM fn_listextendedproperty(default, default, default, default, default, default, default)
2023-09-15 23:08:24,092 INFO sqlalchemy.engine.Engine [generated in 0.00065s] ()
2023-09-15 23:08:24,094 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-09-15 23:08:24,094 INFO sqlalchemy.engine.Engine IF (SCHEMA_ID('mushroom_exp1') IS NOT NULL) BEGIN DROP SCHEMA [mushroom_exp1]; END
2023-09-15 23:08:24,094 INFO sqlalchemy.engine.Engine [generated in 0.00099s] ()
2023-09-15 23:08:24,096 INFO sqlalchemy.engine.Engine CREATE SCHEMA [mushroom_exp1] AUTHORIZATION [dbo]
2023-09-15 23:08:24,096 INFO sqlalchemy.engine.Engine [generated in 0.00046s] ()
2023-09-15 23:08:24,104 INFO sqlalchemy.engine.Engine SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]
FROM [INFORMATION_SCHEMA].[TABLES]
WHERE ([INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) OR [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max))) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max))
2023-09-15 23:08:24,104 INFO sqlalchemy.engine.Engine [generated in 0.00079s] ('BASE TABLE', 'VIEW', 'mushroom', 'mushroom_exp1')
2023-09-15 23:08:24,107 INFO sqlalchemy.engine.Engine
CREATE TABLE mushroom_exp1.mushroom (
	class VARCHAR(max) NULL,
	mushroom_id BIGINT NULL,
	cap_id BIGINT NULL,
	gill_id BIGINT NULL,
	stalk_id BIGINT NULL,
	veil_id BIGINT NULL,
	ring_id BIGINT NULL,
	spore_print_color_type_id BIGINT NULL,
	bruises_type_id BIGINT NULL,
	odor_type_id BIGINT NULL,
	population_type_id BIGINT NULL,
	habitat_type_id BIGINT NULL
)


2023-09-15 23:08:24,108 INFO sqlalchemy.engine.Engine [no key 0.00072s] ()
2023-09-15 23:08:24,315 INFO sqlalchemy.engine.Engine INSERT INTO mushroom_exp1.mushroom (class, mushroom_id, cap_id, gill_id, stalk_id, veil_id, ring_id, spore_print_color_type_id, bruises_type_id, odor_type_id, population_type_id, habitat_type_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ... 6463 characters truncated ...  ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-09-15 23:08:24,315 INFO sqlalchemy.engine.Engine [generated in 0.19132s (insertmanyvalues) 1/47 (unordered)] ('p', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'e', 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 'e', 2, 2, 2, 1, 0, 0, 1, 0, 2, 1, 2, 'p', 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 'e', 4 ... 1988 parameters truncated ... 0, 1, 'e', 170, 20, 14, 0, 0, 0, 1, 1, 3, 4, 0, 'e', 171, 7, 1, 1, 0, 0, 1, 0, 2, 0, 1, 'e', 172, 15, 9, 4, 0, 0, 2, 0, 2, 3, 3, 'e', 173, 12, 7, 1, 0, 0, 0, 0, 1, 0, 1)
2023-09-15 23:08:24,386 INFO sqlalchemy.engine.Engine INSERT INTO mushroom_exp1.mushroom (class, mushroom_id, cap_id, gill_id, stalk_id, veil_id, ring_id, spore_print_color_type_id, bruises_type_id, odor_type_id, population_type_id, habitat_type_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ... 6463 characters truncated ...  ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-09-15 23:08:24,387 INFO sqlalchemy.engine.Engine [insertmanyvalues 2/47 (unordered)] ('e', 174, 17, 10, 5, 0, 0, 1, 0, 2, 0, 1, 'e', 175, 6, 7, 1, 0, 0, 0, 0, 2, 1, 2, 'e', 176, 6, 1, 1, 0, 0, 0, 0, 1, 1, 2, 'e', 177, 12, 5, 1, 0, 0, 1, 0, 1, 0, 1, 'e', 178 ... 1988 parameters truncated ... 3, 3, 'e', 344, 12, 5, 1, 0, 0, 1, 0, 2, 0, 1, 'e', 345, 8, 8, 3, 0, 1, 1, 1, 3, 2, 1, 'e', 346, 15, 9, 4, 0, 0, 1, 0, 2, 3, 3, 'e', 347, 1, 2, 1, 0, 0, 1, 0, 1, 1, 2)
2023-09-15 23:08:24,395 INFO sqlalchemy.engine.Engine INSERT INTO mushroom_exp1.mushroom (class, mushroom_id, cap_id, gill_id, stalk_id, veil_id, ring_id, spore_print_color_type_id, bruises_type_id, odor_type_id, population_type_id, habitat_type_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ... 6463 characters truncated ...  ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-09-15 23:08:24,396 INFO sqlalchemy.engine.Engine [insertmanyvalues 3/47 (unordered)] ('e', 348, 26, 8, 3, 0, 1, 0, 1, 3, 0, 1, 'e', 349, 8, 14, 0, 0, 0, 1, 1, 3, 4, 0, 'e', 350, 26, 16, 7, 0, 1, 1, 1, 3, 2, 1, 'e', 351, 23, 10, 5, 0, 0, 1, 0, 1, 0, 4, 'e', 352 ... 1988 parameters truncated ... 1, 1, 'e', 518, 3, 1, 1, 0, 0, 0, 0, 2, 0, 1, 'e', 519, 5, 1, 1, 0, 0, 1, 0, 1, 1, 1, 'e', 520, 16, 7, 1, 0, 0, 0, 0, 2, 1, 2, 'e', 521, 2, 2, 1, 0, 0, 0, 0, 2, 0, 1)
2023-09-15 23:08:24,404 INFO sqlalchemy.engine.Engine INSERT INTO mushroom_exp1.mushroom (class, mushroom_id, cap_id, gill_id, stalk_id, veil_id, ring_id, spore_print_color_type_id, bruises_type_id, odor_type_id, population_type_id, habitat_type_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ... 6463 characters truncated ...  ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-09-15 23:08:24,405 INFO sqlalchemy.engine.Engine [insertmanyvalues 4/47 (unordered)] ('e', 522, 17, 10, 5, 0, 0, 1, 0, 1, 4, 4, 'p', 523, 0, 3, 0, 0, 0, 1, 0, 0, 0, 0, 'e', 524, 18, 3, 0, 0, 0, 0, 1, 3, 4, 0, 'e', 525, 7, 7, 1, 0, 0, 1, 0, 2, 0, 1, 'e', 526 ... 1988 parameters truncated ... 0, 1, 'e', 692, 11, 10, 5, 0, 0, 1, 0, 1, 0, 4, 'e', 693, 26, 4, 6, 0, 1, 1, 1, 3, 2, 1, 'p', 694, 11, 6, 0, 0, 0, 1, 0, 0, 0, 1, 'e', 695, 6, 2, 1, 0, 0, 1, 0, 1, 0, 1)
2023-09-15 23:08:24,415 INFO sqlalchemy.engine.Engine INSERT INTO mushroom_exp1.mushroom (class, mushroom_id, cap_id, gill_id, stalk_id, veil_id, ring_id, spore_print_color_type_id, bruises_type_id, odor_type_id, population_type_id, habitat_type_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ... 6463 characters truncated ...  ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-09-15 23:08:24,416 INFO sqlalchemy.engine.Engine [insertmanyvalues 5/47 (unordered)] ('e', 696, 7, 7, 1, 0, 0, 1, 0, 1, 0, 2, 'p', 697, 11, 12, 0, 0, 0, 0, 0, 0, 3, 1, 'p', 698, 0, 6, 0, 0, 0, 1, 0, 0, 3, 0, 'e', 699, 19, 8, 6, 0, 1, 1, 1, 3, 2, 1, 'p', 700 ... 1988 parameters truncated ... 0, 1, 'e', 866, 14, 3, 0, 0, 0, 1, 1, 3, 3, 0, 'e', 867, 17, 10, 5, 0, 0, 1, 0, 2, 4, 4, 'e', 868, 20, 6, 0, 0, 0, 1, 1, 3, 4, 0, 'e', 869, 1, 1, 1, 0, 0, 1, 0, 2, 1, 1)
2023-09-15 23:08:24,450 INFO sqlalchemy.engine.Engine INSERT INTO mushroom_exp1.mushroom (class, mushroom_id, cap_id, gill_id, stalk_id, veil_id, ring_id, spore_print_color_type_id, bruises_type_id, odor_type_id, population_type_id, habitat_type_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ... 6463 characters truncated ...  ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-09-15 23:08:24,451 INFO sqlalchemy.engine.Engine [insertmanyvalues 6/47 (unordered)] ('e', 870, 23, 10, 5, 0, 0, 0, 0, 1, 4, 4, 'e', 871, 1, 7, 1, 0, 0, 1, 0, 2, 1, 1, 'e', 872, 5, 1, 1, 0, 0, 1, 0, 1, 0, 2, 'e', 873, 8, 2, 10, 0, 0, 0, 0, 3, 3, 3, 'e', 874 ... 1988 parameters truncated ... 0, 0, 'e', 1040, 5, 7, 5, 0, 0, 1, 0, 1, 4, 4, 'e', 1041, 23, 2, 5, 0, 0, 0, 0, 1, 0, 4, 'e', 1042, 25, 16, 2, 0, 1, 0, 1, 3, 2, 1, 'e', 1043, 11, 17, 15, 0, 0, 1, 0, 3, 3, 3)
2023-09-15 23:08:24,462 INFO sqlalchemy.engine.Engine INSERT INTO mushroom_exp1.mushroom (class, mushroom_id, cap_id, gill_id, stalk_id, veil_id, ring_id, spore_print_color_type_id, bruises_type_id, odor_type_id, population_type_id, habitat_type_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ... 6463 characters truncated ...  ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-09-15 23:08:24,463 INFO sqlalchemy.engine.Engine [insertmanyvalues 7/47 (unordered)] ('e', 1044, 4, 16, 7, 0, 1, 1, 1, 3, 2, 1, 'e', 1045, 16, 7, 1, 0, 0, 1, 0, 1, 0, 1, 'e', 1046, 20, 16, 3, 0, 1, 1, 1, 3, 0, 1, 'p', 1047, 23, 3, 0, 0, 0, 1, 0, 0, 0, 0, 'e', 1048 ... 1988 parameters truncated ... 2, 1, 'e', 1214, 8, 8, 2, 0, 1, 0, 1, 3, 2, 1, 'p', 1215, 19, 0, 0, 0, 0, 1, 0, 0, 3, 1, 'e', 1216, 16, 15, 7, 0, 1, 1, 1, 3, 2, 1, 'e', 1217, 14, 15, 6, 0, 1, 0, 1, 3, 0, 1)
2023-09-15 23:08:24,471 INFO sqlalchemy.engine.Engine INSERT INTO mushroom_exp1.mushroom (class, mushroom_id, cap_id, gill_id, stalk_id, veil_id, ring_id, spore_print_color_type_id, bruises_type_id, odor_type_id, population_type_id, habitat_type_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ... 6463 characters truncated ...  ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-09-15 23:08:24,471 INFO sqlalchemy.engine.Engine [insertmanyvalues 8/47 (unordered)] ('e', 1218, 10, 16, 7, 0, 1, 1, 1, 3, 2, 1, 'e', 1219, 10, 4, 7, 0, 1, 1, 1, 3, 0, 1, 'e', 1220, 5, 2, 5, 0, 0, 0, 0, 1, 0, 1, 'e', 1221, 4, 4, 7, 0, 1, 1, 1, 3, 0, 1, 'e', 1222 ... 1988 parameters truncated ... 3, 3, 'e', 1388, 8, 10, 8, 0, 0, 0, 0, 3, 3, 3, 'e', 1389, 8, 4, 3, 0, 1, 1, 1, 3, 0, 1, 'e', 1390, 20, 7, 10, 0, 0, 0, 0, 3, 4, 3, 'e', 1391, 16, 16, 2, 0, 1, 1, 1, 3, 0, 1)
2023-09-15 23:08:24,479 INFO sqlalchemy.engine.Engine INSERT INTO mushroom_exp1.mushroom (class, mushroom_id, cap_id, gill_id, stalk_id, veil_id, ring_id, spore_print_color_type_id, bruises_type_id, odor_type_id, population_type_id, habitat_type_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ... 6463 characters truncated ...  ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-09-15 23:08:24,480 INFO sqlalchemy.engine.Engine [insertmanyvalues 9/47 (unordered)] ('e', 1392, 13, 16, 7, 0, 1, 0, 1, 3, 2, 1, 'e', 1393, 16, 15, 6, 0, 1, 0, 1, 3, 0, 1, 'e', 1394, 18, 4, 3, 0, 1, 0, 1, 3, 0, 1, 'e', 1395, 8, 10, 14, 0, 0, 1, 0, 3, 4, 3, 'e', 1396 ... 1988 parameters truncated ... 0, 1, 'e', 1562, 8, 15, 6, 0, 1, 0, 1, 3, 2, 1, 'e', 1563, 8, 10, 13, 0, 0, 1, 0, 3, 3, 3, 'e', 1564, 6, 5, 1, 0, 0, 1, 0, 2, 1, 2, 'e', 1565, 20, 2, 10, 0, 0, 1, 0, 3, 3, 3)
2023-09-15 23:08:24,488 INFO sqlalchemy.engine.Engine INSERT INTO mushroom_exp1.mushroom (class, mushroom_id, cap_id, gill_id, stalk_id, veil_id, ring_id, spore_print_color_type_id, bruises_type_id, odor_type_id, population_type_id, habitat_type_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ... 6463 characters truncated ...  ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-09-15 23:08:24,489 INFO sqlalchemy.engine.Engine [insertmanyvalues 10/47 (unordered)] ('p', 1566, 23, 6, 0, 0, 0, 0, 0, 0, 0, 1, 'e', 1567, 16, 16, 2, 0, 1, 1, 1, 3, 2, 1, 'p', 1568, 19, 0, 0, 0, 0, 0, 0, 0, 3, 0, 'e', 1569, 19, 8, 3, 0, 1, 1, 1, 3, 2, 1, 'e', 1570 ... 1988 parameters truncated ... 2, 1, 'e', 1736, 0, 15, 6, 0, 1, 0, 1, 3, 2, 1, 'e', 1737, 8, 17, 8, 0, 0, 0, 0, 3, 3, 3, 'e', 1738, 13, 15, 6, 0, 1, 0, 1, 3, 0, 1, 'p', 1739, 13, 6, 0, 0, 0, 1, 0, 0, 3, 0)
2023-09-15 23:08:24,498 INFO sqlalchemy.engine.Engine INSERT INTO mushroom_exp1.mushroom (class, mushroom_id, cap_id, gill_id, stalk_id, veil_id, ring_id, spore_print_color_type_id, bruises_type_id, odor_type_id, population_type_id, habitat_type_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ... 6463 characters truncated ...  ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-09-15 23:08:24,499 INFO sqlalchemy.engine.Engine [insertmanyvalues 11/47 (unordered)] ('e', 1740, 25, 16, 3, 0, 1, 0, 1, 3, 2, 1, 'e', 1741, 14, 16, 2, 0, 1, 1, 1, 3, 0, 1, 'e', 1742, 26, 15, 7, 0, 1, 1, 1, 3, 0, 1, 'e', 1743, 25, 8, 7, 0, 1, 0, 1, 3, 2, 1, 'e', 1744 ... 1988 parameters truncated ... 0, 1, 'e', 1910, 28, 10, 10, 0, 0, 0, 0, 3, 3, 3, 'e', 1911, 27, 17, 15, 0, 0, 0, 0, 3, 3, 3, 'e', 1912, 28, 2, 8, 0, 0, 0, 0, 3, 3, 3, 'e', 1913, 20, 16, 2, 0, 1, 0, 1, 3, 0, 1)
2023-09-15 23:08:24,508 INFO sqlalchemy.engine.Engine INSERT INTO mushroom_exp1.mushroom (class, mushroom_id, cap_id, gill_id, stalk_id, veil_id, ring_id, spore_print_color_type_id, bruises_type_id, odor_type_id, population_type_id, habitat_type_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ... 6463 characters truncated ...  ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-09-15 23:08:24,508 INFO sqlalchemy.engine.Engine [insertmanyvalues 12/47 (unordered)] ('e', 1914, 18, 15, 6, 0, 1, 1, 1, 3, 2, 1, 'e', 1915, 17, 10, 5, 0, 0, 1, 0, 2, 4, 1, 'p', 1916, 29, 12, 0, 0, 0, 0, 0, 0, 3, 0, 'e', 1917, 19, 16, 7, 0, 1, 0, 1, 3, 2, 1, 'e', 1918 ... 1988 parameters truncated ... 3, 3, 'e', 2084, 18, 8, 3, 0, 1, 0, 1, 3, 0, 1, 'e', 2085, 18, 8, 2, 0, 1, 0, 1, 3, 0, 1, 'e', 2086, 14, 16, 7, 0, 1, 1, 1, 3, 0, 1, 'e', 2087, 20, 10, 10, 0, 0, 0, 0, 3, 4, 3)
2023-09-15 23:08:24,516 INFO sqlalchemy.engine.Engine INSERT INTO mushroom_exp1.mushroom (class, mushroom_id, cap_id, gill_id, stalk_id, veil_id, ring_id, spore_print_color_type_id, bruises_type_id, odor_type_id, population_type_id, habitat_type_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ... 6463 characters truncated ...  ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-09-15 23:08:24,517 INFO sqlalchemy.engine.Engine [insertmanyvalues 13/47 (unordered)] ('e', 2088, 30, 2, 13, 0, 0, 1, 0, 3, 4, 3, 'p', 2089, 23, 6, 0, 0, 0, 0, 0, 0, 0, 0, 'e', 2090, 27, 10, 15, 0, 0, 0, 0, 3, 3, 3, 'e', 2091, 16, 4, 3, 0, 1, 1, 1, 3, 2, 1, 'e', 2092 ... 1988 parameters truncated ... 3, 3, 'e', 2258, 28, 17, 9, 0, 0, 1, 0, 3, 3, 3, 'e', 2259, 11, 2, 12, 0, 0, 1, 0, 3, 3, 3, 'e', 2260, 26, 8, 6, 0, 1, 1, 1, 3, 2, 1, 'e', 2261, 8, 7, 14, 0, 0, 0, 0, 3, 4, 3)
2023-09-15 23:08:24,525 INFO sqlalchemy.engine.Engine INSERT INTO mushroom_exp1.mushroom (class, mushroom_id, cap_id, gill_id, stalk_id, veil_id, ring_id, spore_print_color_type_id, bruises_type_id, odor_type_id, population_type_id, habitat_type_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ... 6463 characters truncated ...  ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-09-15 23:08:24,525 INFO sqlalchemy.engine.Engine [insertmanyvalues 14/47 (unordered)] ('e', 2262, 14, 2, 11, 0, 0, 0, 0, 3, 4, 3, 'e', 2263, 28, 7, 12, 0, 0, 1, 0, 3, 4, 3, 'e', 2264, 28, 7, 13, 0, 0, 0, 0, 3, 4, 3, 'e', 2265, 11, 2, 9, 0, 0, 0, 0, 3, 4, 3, 'e', 2266 ... 1988 parameters truncated ... 4, 3, 'e', 2432, 20, 7, 11, 0, 0, 1, 0, 3, 4, 3, 'e', 2433, 20, 2, 9, 0, 0, 1, 0, 3, 4, 3, 'e', 2434, 20, 10, 10, 0, 0, 0, 0, 3, 3, 3, 'e', 2435, 20, 17, 13, 0, 0, 1, 0, 3, 4, 3)
2023-09-15 23:08:24,538 INFO sqlalchemy.engine.Engine INSERT INTO mushroom_exp1.mushroom (class, mushroom_id, cap_id, gill_id, stalk_id, veil_id, ring_id, spore_print_color_type_id, bruises_type_id, odor_type_id, population_type_id, habitat_type_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ... 6463 characters truncated ...  ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-09-15 23:08:24,539 INFO sqlalchemy.engine.Engine [insertmanyvalues 15/47 (unordered)] ('e', 2436, 18, 10, 11, 0, 0, 1, 0, 3, 4, 3, 'e', 2437, 30, 17, 11, 0, 0, 1, 0, 3, 3, 3, 'e', 2438, 23, 10, 13, 0, 0, 0, 0, 3, 4, 3, 'e', 2439, 31, 17, 10, 0, 0, 0, 0, 3, 3, 3, 'e', 2440 ... 1988 parameters truncated ... 3, 4, 'e', 2606, 30, 10, 9, 0, 0, 1, 0, 3, 3, 3, 'e', 2607, 14, 2, 15, 0, 0, 1, 0, 3, 3, 3, 'e', 2608, 30, 2, 14, 0, 0, 0, 0, 3, 4, 3, 'e', 2609, 30, 2, 11, 0, 0, 1, 0, 3, 3, 3)
2023-09-15 23:08:24,547 INFO sqlalchemy.engine.Engine INSERT INTO mushroom_exp1.mushroom (class, mushroom_id, cap_id, gill_id, stalk_id, veil_id, ring_id, spore_print_color_type_id, bruises_type_id, odor_type_id, population_type_id, habitat_type_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ... 6463 characters truncated ...  ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-09-15 23:08:24,548 INFO sqlalchemy.engine.Engine [insertmanyvalues 16/47 (unordered)] ('e', 2610, 28, 10, 12, 0, 0, 0, 0, 3, 4, 3, 'e', 2611, 33, 7, 9, 0, 0, 1, 0, 3, 3, 3, 'e', 2612, 14, 17, 11, 0, 0, 1, 0, 3, 4, 3, 'e', 2613, 20, 2, 15, 0, 0, 1, 0, 3, 4, 3, 'e', 2614 ... 1988 parameters truncated ... 3, 3, 'e', 2780, 14, 17, 8, 0, 0, 0, 0, 3, 4, 3, 'e', 2781, 28, 10, 8, 0, 0, 1, 0, 3, 3, 3, 'e', 2782, 20, 17, 10, 0, 0, 0, 0, 3, 4, 3, 'e', 2783, 18, 10, 9, 0, 0, 0, 0, 3, 4, 3)
2023-09-15 23:08:24,557 INFO sqlalchemy.engine.Engine INSERT INTO mushroom_exp1.mushroom (class, mushroom_id, cap_id, gill_id, stalk_id, veil_id, ring_id, spore_print_color_type_id, bruises_type_id, odor_type_id, population_type_id, habitat_type_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ... 6463 characters truncated ...  ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-09-15 23:08:24,557 INFO sqlalchemy.engine.Engine [insertmanyvalues 17/47 (unordered)] ('e', 2784, 18, 10, 15, 0, 0, 0, 0, 3, 3, 3, 'e', 2785, 14, 2, 10, 0, 0, 0, 0, 3, 4, 3, 'e', 2786, 8, 7, 9, 0, 0, 1, 0, 3, 4, 3, 'e', 2787, 28, 7, 15, 0, 0, 1, 0, 3, 4, 3, 'e', 2788 ... 1988 parameters truncated ... 4, 3, 'e', 2954, 30, 10, 11, 0, 0, 1, 0, 3, 4, 3, 'e', 2955, 14, 2, 14, 0, 0, 1, 0, 3, 3, 3, 'e', 2956, 28, 2, 13, 0, 0, 0, 0, 3, 4, 3, 'e', 2957, 8, 2, 10, 0, 0, 0, 0, 3, 4, 3)
2023-09-15 23:08:24,573 INFO sqlalchemy.engine.Engine INSERT INTO mushroom_exp1.mushroom (class, mushroom_id, cap_id, gill_id, stalk_id, veil_id, ring_id, spore_print_color_type_id, bruises_type_id, odor_type_id, population_type_id, habitat_type_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ... 6463 characters truncated ...  ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-09-15 23:08:24,573 INFO sqlalchemy.engine.Engine [insertmanyvalues 18/47 (unordered)] ('e', 2958, 30, 7, 14, 0, 0, 1, 0, 3, 4, 3, 'e', 2959, 30, 7, 13, 0, 0, 0, 0, 3, 3, 3, 'e', 2960, 8, 17, 10, 0, 0, 0, 0, 3, 3, 3, 'e', 2961, 11, 2, 10, 0, 0, 1, 0, 3, 4, 3, 'e', 2962 ... 1988 parameters truncated ... 3, 3, 'e', 3128, 32, 7, 13, 0, 0, 1, 0, 3, 3, 3, 'e', 3129, 23, 7, 9, 0, 0, 1, 0, 3, 4, 3, 'e', 3130, 33, 10, 15, 0, 0, 0, 0, 3, 3, 3, 'e', 3131, 23, 17, 11, 0, 0, 1, 0, 3, 4, 3)
2023-09-15 23:08:24,581 INFO sqlalchemy.engine.Engine INSERT INTO mushroom_exp1.mushroom (class, mushroom_id, cap_id, gill_id, stalk_id, veil_id, ring_id, spore_print_color_type_id, bruises_type_id, odor_type_id, population_type_id, habitat_type_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ... 6463 characters truncated ...  ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-09-15 23:08:24,582 INFO sqlalchemy.engine.Engine [insertmanyvalues 19/47 (unordered)] ('e', 3132, 33, 10, 14, 0, 0, 0, 0, 3, 4, 3, 'e', 3133, 33, 17, 8, 0, 0, 1, 0, 3, 3, 3, 'e', 3134, 8, 17, 14, 0, 0, 0, 0, 3, 4, 3, 'e', 3135, 31, 10, 14, 0, 0, 0, 0, 3, 4, 3, 'e', 3136 ... 1988 parameters truncated ... 4, 3, 'e', 3302, 33, 17, 13, 0, 0, 1, 0, 3, 4, 3, 'e', 3303, 18, 7, 13, 0, 0, 1, 0, 3, 3, 3, 'p', 3304, 20, 5, 23, 0, 2, 3, 1, 4, 3, 1, 'e', 3305, 31, 2, 8, 0, 0, 1, 0, 3, 3, 3)